-- NOPPARAT PENGSUK
-- SECTION 2
-- 6288103
-- PARCTICE SQL

/*1*/SELECT * FROM professor; SELECT * FROM department;
/*2*/SELECT STU_FNAME,STU_LNAME FROM student;
/*3*/SELECT STU_FNAME AS Firstname , STU_LNAME AS Lastname FROM student;
/*4*/SELECT DISTINCT STU_FNAME AS Firstname FROM student;
/*5*/SELECT COURSE_CODE,CRS_CREDIT FROM course;
/*6*/SELECT CLASS_CODE,COURSE_CODE,CLASS_ROOM FROM class;
/*7*/SELECT DISTINCT CLASS_ROOM AS Classroom, COURSE_CODE AS "Course code" FROM class LIMIT 5;
/*8*/SELECT DISTINCT EMP_NUM AS "Employee name", COURSE_CODE AS "Teacing course" FROM class;
/*9*/SELECT EMP_FNAME AS Firstname, EMP_LNAME AS Lastname,EMP_DOB AS DoB FROM professor LIMIT 10;
/*10*/SELECT EMP_FNAME AS Firstname, EMP_LNAME AS Lastname,YEAR(EMP_DOB) AS "Year" FROM professor LIMIT 10;
/*11*/SELECT EMP_FNAME AS Firstname, EMP_LNAME AS Lastname,(2020 - YEAR(EMP_DOB)) AS Age FROM professor LIMIT 10;
/*12*/SELECT * FROM course ORDER BY CRS_CREDIT ASC;
/*13*/SELECT STU_FNAME AS Firstname,STU_LNAME AS Lastname, STU_GPA AS GPA FROM student ORDER BY STU_GPA DESC LIMIT 3;
/*14*/SELECT STU_FNAME AS Firstname,STU_LNAME AS Lastname, STU_GPA AS GPA FROM student WHERE STU_GPA>=3.50;
/*15*/SELECT STU_FNAME AS Firstname,STU_LNAME AS Lastname, STU_GPA AS GPA FROM student WHERE STU_GPA BETWEEN 3.25 AND 3.5;
/*16*/SELECT STU_FNAME AS Firstname,STU_LNAME AS Lastname, STU_GPA AS GPA FROM student WHERE STU_GPA>=1.50 AND STU_GPA < 1.80;
/*17*/SELECT STU_FNAME AS Firstname,STU_LNAME AS Lastname, STU_GPA AS GPA FROM student WHERE STU_GPA>=1.80 AND STU_GPA < 2;
/*18*/SELECT STU_FNAME AS Firstname,STU_LNAME AS Lastname  FROM student WHERE STU_GPA IS NULL;
/*19*/SELECT STU_FNAME AS Firstname,STU_LNAME AS Lastname  FROM student WHERE STU_DOB BETWEEN DATE("1970-01-01") AND DATE("1979-12-31");
/*20*/SELECT * FROM student WHERE STU_FNAME LIKE "A%" AND DEPT_CODE = "CIS";
/*21*/SELECT * FROM course WHERE COURSE_NAME LIKE "Intro.%";
/*22*/SELECT CLASS_CODE,COURSE_CODE,CLASS_TIME FROM class WHERE CLASS_SECTION = 2 AND CLASS_TIME LIKE "MWF%";
/*23*/SELECT COURSE_CODE,COURSE_NAME,DEPT_CODE FROM course WHERE DEPT_CODE IN ("CIS", "ENG", "MATH") ORDER BY DEPT_CODE ASC;
/*24*/SELECT CLASS_CODE,COURSE_CODE,EMP_NUM FROM class WHERE EMP_NUM IN (104,105,106,155) ORDER BY EMP_NUM ASC;